server:
  port: 8002
oss:
  accessKeyId: LTAI4GHURXQrxTVQAVumWuqT
  accessKeyScret: q5ZxnxSVIMVK8WP9FR1KZtgQDjmfJ3
  endPoint: https://oss-cn-beijing.aliyuncs.com
  bucketName: lxfoos
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
